// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmQqdXVFIVO9ght9Ekg5WCh3eWFH7xcxw',
    appId: '1:507750877993:web:392e2b56145e34608ac538',
    messagingSenderId: '507750877993',
    projectId: 'movie-application-01',
    authDomain: 'movie-application-01.firebaseapp.com',
    storageBucket: 'movie-application-01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8gBkzT0CKlvHxCR6wg9RR10SGmfUaaLY',
    appId: '1:507750877993:android:4ffb04048244be2a8ac538',
    messagingSenderId: '507750877993',
    projectId: 'movie-application-01',
    storageBucket: 'movie-application-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGzOeOdAjVVNhkNpEQdd5K_9XC3rOXU90',
    appId: '1:507750877993:ios:1ff43daedd35ed198ac538',
    messagingSenderId: '507750877993',
    projectId: 'movie-application-01',
    storageBucket: 'movie-application-01.firebasestorage.app',
    iosBundleId: 'com.example.movieApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGzOeOdAjVVNhkNpEQdd5K_9XC3rOXU90',
    appId: '1:507750877993:ios:1ff43daedd35ed198ac538',
    messagingSenderId: '507750877993',
    projectId: 'movie-application-01',
    storageBucket: 'movie-application-01.firebasestorage.app',
    iosBundleId: 'com.example.movieApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmQqdXVFIVO9ght9Ekg5WCh3eWFH7xcxw',
    appId: '1:507750877993:web:762117c93ec3a3968ac538',
    messagingSenderId: '507750877993',
    projectId: 'movie-application-01',
    authDomain: 'movie-application-01.firebaseapp.com',
    storageBucket: 'movie-application-01.firebasestorage.app',
  );
}
